basePath: /
definitions:
  dao.Book:
    properties:
      author:
        description: 作者
        type: string
      author_introduction:
        description: 作者简介
        type: string
      book_name:
        description: 书名
        type: string
      brief_introduction:
        description: 内容简介
        type: string
      count:
        description: 库存
        type: integer
      del_flg:
        description: 删除标识
        type: integer
      id:
        description: 书的ID
        type: integer
      img_url:
        description: 封面地址
        type: string
      isbn:
        description: ISBN号码
        type: string
      pages:
        description: 页数
        type: integer
      price:
        description: 价格
        type: number
      publish_date:
        description: 出版时间
        type: string
      publishing_house:
        description: 出版社
        type: string
      translator:
        description: 译者
        type: string
    type: object
  tools.HttpCode:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: 127.0.0.1
info:
  contact: {}
  description: 该项目用户设有游客，普通用户和管理员，但是只有普通用户和管理员可以借阅书籍
  title: 图书馆管理系统
  version: "1.0"
paths:
  /:
    get:
      description: 获取所有图书信息
      parameters:
      - description: 需要查询的页数
        in: query
        name: page
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/tools.HttpCode'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dao.Book'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/tools.HttpCode'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dao.Book'
                  type: array
              type: object
      summary: 获取所有图书信息
      tags:
      - library
  /{book_name}:
    get:
      consumes:
      - application/json
      description: 通过模糊查询查看图书信息学
      parameters:
      - description: 书名
        in: path
        name: book_name
        required: true
        type: string
      - description: 页数
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/tools.HttpCode'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dao.Book'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/tools.HttpCode'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/dao.Book'
                  type: array
              type: object
      summary: 获取图书信息
      tags:
      - library
  /log/login:
    post:
      description: 用户登录
      parameters:
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: pwd
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 用户登录
      tags:
      - login
  /log/logout:
    get:
      description: 用户退出登录
      responses: {}
      summary: 用户退出登录
      tags:
      - login
  /log/register:
    post:
      description: 用户注册
      parameters:
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: pwd
        type: string
      - description: 0:普通用户，1:超级用户
        in: formData
        name: type
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 用户注册
      tags:
      - login
  /manager:
    get:
      description: 查看所有借阅记录
      parameters:
      - default: "123"
        description: Debug header
        in: header
        name: Debug
        type: string
      - description: 页数
        in: query
        name: page
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 查看所有借阅记录
      tags:
      - manager
  /manager/book:
    post:
      description: 管理员添加图书信息
      parameters:
      - description: 图书ID
        in: formData
        name: id
        type: integer
      - description: 书名
        in: formData
        name: book_name
        type: string
      - description: 作者
        in: formData
        name: author
        type: string
      - description: 出版社
        in: formData
        name: publishing_house
        type: string
      - description: 译者
        in: formData
        name: translator
        type: string
      - description: 日期：2002-03-02
        in: formData
        name: publish_data
        required: true
        type: string
      - description: 页数
        in: formData
        name: pages
        type: integer
      - description: isbn编号
        in: formData
        name: isbn
        type: string
      - description: 价格
        in: formData
        name: price
        type: number
      - description: 图书简介
        in: formData
        name: brief_introduction
        type: string
      - description: 作者简介
        in: formData
        name: author_introduction
        type: string
      - description: 图片链接
        in: formData
        name: img_url
        type: string
      - description: 图书数量
        in: formData
        name: count
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 添加图书
      tags:
      - manager
  /manager/book/{book_id}:
    delete:
      description: 管理员删除指定书名的图书信息
      parameters:
      - default: "123"
        description: Debug header
        in: header
        name: Debug
        type: string
      - description: 书名
        in: path
        name: book_id
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 删除图书信息
      tags:
      - manager
  /manager/user:
    get:
      description: 查看所有用户信息
      parameters:
      - default: "123"
        description: Debug header
        in: header
        name: Debug
        type: string
      - description: 页数
        in: query
        name: page
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 查看所有用户信息
      tags:
      - manager
  /manager/user/{id}:
    get:
      description: 查看指定用户的借阅信息
      parameters:
      - default: "123"
        description: Debug header
        in: header
        name: Debug
        type: string
      - description: 页数
        in: query
        name: page
        type: string
      - description: 用户Id
        in: path
        name: id
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 查看指定用户的借阅信息
      tags:
      - manager
  /user:
    get:
      description: 查看用户信息
      parameters:
      - default: "123"
        description: Debug header
        in: header
        name: Debug
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 查看用户信息
      tags:
      - user
    put:
      description: 修改用户信息
      parameters:
      - default: "123"
        description: Debug header
        in: header
        name: Debug
        type: string
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: pwd
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 修改用户信息
      tags:
      - user
  /user/book:
    get:
      description: 查看自己的借阅记录
      parameters:
      - default: "123"
        description: Debug header
        in: header
        name: Debug
        type: string
      - description: 页数
        in: query
        name: page
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 查看自己的借阅记录
      tags:
      - user
  /user/book/{book_id}:
    get:
      description: 归还指定书名的图书
      parameters:
      - default: "123"
        description: Debug
        in: header
        name: Debug
        type: string
      - description: 图书ID
        in: path
        name: book_id
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 归还图书
      tags:
      - user
    post:
      description: 借阅指定书名的图书
      parameters:
      - default: "123"
        description: Debug header
        in: header
        name: Debug
        type: string
      - description: 图书ID
        in: path
        name: book_id
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tools.HttpCode'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/tools.HttpCode'
      summary: 借阅图书
      tags:
      - user
swagger: "2.0"
